'use strict';
(() => {
const D=window.REVIEW_DATA;if(!D)throw Error('Prüfdaten fehlen.');
const $=id=>document.getElementById(id), key='autorenpruefung-'+D.package_id;
let state={schema:'autorenpruefung-v1',package_id:D.package_id,reviewer:'',answers:{},history:[],sessions:[],position:D.cases[0].id};
let storageOK=true, visible=[], current=null, sourceFull='',dirty=false, fieldIndex=0;
try{const s=localStorage.getItem(key);if(s){const x=JSON.parse(s);if(x.package_id===D.package_id)state={...state,...x};}}catch(e){storageOK=false;}
const labels={id:'Kennung',itemId:'Kennung',statement:'Aussage',text:'Text',proposition:'Aussage',sourceUnitIds:'Angegebene Quell-Units',evidence:'Gespeicherte Zitate',quote:'Zitat',source:'Quelle',finding:'Agentenvorschlag',herleitung:'Herleitung',ankerIds:'Bestandsanker',disposition:'Einordnung',kategorie:'Kategorie',linse:'Perspektive',pbi:'Arbeitspaket',title:'Titel',goal:'Ziel',acceptanceCriteria:'Akzeptanzkriterien',itemType:'Elementtyp',status:'Status',rationale:'Begründung',reason:'Begründung',note:'Hinweis',sourceRunId:'Ursprungslauf',version:'Version',raw:'Vollständiges Ursprungsobjekt',before:'Vorher',after:'Nachher',field:'Feld',present:'Im damaligen Bestand vorhanden',item:'Bestandselement',relationType:'Beziehungstyp',fromId:'Von',toId:'Zu',metadata:'Weitere Metadaten',body:'Vollständiger Issue-Text',sourceClaimIds:'Claim-Verweise',proposedStatement:'Vorgeschlagener Text',proposedTitle:'Vorgeschlagener Titel',proposedAcceptanceCriteria:'Vorgeschlagene Akzeptanzkriterien',decision:'Entscheidung',content:'Soll-Inhalt',origin_group:'Alt- oder Neuinhalt',reference:'Referenz',kind:'Operationsart'};
const valueLabels={full:'Vollständig abgedeckt',partial:'Teilweise abgedeckt',none:'Nicht abgedeckt',E:'Erfüllt',T:'Teilweise',N:'Nicht erfüllt',NB:'Nicht beurteilbar',NA:'Nicht anwendbar',F:'Funktion / Berechtigung / Ablauf',U:'Darstellung / Bediengestaltung',Q:'Zweck / Qualitätsziel',O:'Offene Frage / Konkretisierung',no_distortion_found:'Keine Quellenverfälschung festgestellt',distortion_found:'Quellenverfälschung festgestellt',directly_supported:'Direkt vollständig gestützt',inferentially_supported:'Inferenzbasiert vollständig gestützt',partially_supported:'Teilweise gestützt',unsupported:'Nicht gestützt',applicable:'Weiterhin geltender Soll-Inhalt',conflicting:'Widerspricht anderen geltenden Vorgaben',unresolved:'Fortgeltung ungeklärt',gold_escape:'Außerhalb des Referenzbestands'};
const val=v=>v===null||v===undefined?'Kein gesichertes Vorurteil':(valueLabels[v]||String(v));
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function btn(text,fn,cls){const b=el('button',text,cls);b.type='button';b.addEventListener('click',fn);return b;}
function compoundId(c,f){return c.id+'::'+f.key;}
const fields=new Map(D.cases.flatMap(c=>c.fields.map(f=>[compoundId(c,f),{c,f}])));
function isAnswered(a){return a&&['confirmed','corrected','unclear','assessed'].includes(a.status);}
function done(c){return c.fields.every(f=>isAnswered(state.answers[compoundId(c,f)]));}
function summary(){let out={open:0,confirmed:0,corrected:0,unclear:0,assessed:0};for(const id of fields.keys()){const a=state.answers[id];out[isAnswered(a)?a.status:'open']++;}return out;}
function persist(){try{localStorage.setItem(key,JSON.stringify(state));storageOK=true;}catch(e){storageOK=false;} $('saveState').textContent=storageOK?'Antworten im Browser zwischengespeichert':'Zwischenspeicherung nicht verfügbar – Antworten exportieren';dirty=false;updateProgress();}
function updateProgress(){const s=summary(), n=fields.size;const processed=n-s.open;$('total').textContent=processed+' von '+n+' Antwortfeldern bearbeitet · '+s.open+' offen';$('progress').max=n;$('progress').value=processed;$('completion').textContent=s.confirmed+' bestätigt · '+s.corrected+' korrigiert · '+s.assessed+' erstmals selbst bewertet · '+s.unclear+' unklar. '+(s.open===0?'Alle Felder bearbeitet; unklare Urteile und Änderungen müssen vor der Textübernahme bilanziert werden.':'Noch keine vollständige Autorenprüfung.');}
function renderValue(data,container,depth=0){
 if(data===null||data===undefined){container.append(el('p','Nicht vorhanden / nicht dokumentiert','notice'));return;}
 if(typeof data!=='object'){container.append(el('p',String(data),'reason'));return;}
 if(Array.isArray(data)){if(!data.length){container.append(el('p','Keine Einträge.','notice'));return;} data.forEach((x,i)=>{const e=el('div',undefined,'entry');if(x&&typeof x==='object'&&(x.id||x.itemId||x.Kennung))e.append(el('div',x.id||x.itemId||x.Kennung,'id'));renderValue(x,e,depth+1);container.append(e);});return;}
 const dl=el('dl');container.classList.add('object');for(const [k,v] of Object.entries(data)){
 if(k==='raw'||(typeof v==='object'&&v!==null&&depth>=2)||['metadata','history','source','disposition','sourceArtifactId','sourceArtifactType','sourceDecisionId','sourceCandidateId','sourceClaimIds','createdUtc','updatedUtc','createdBy','lastChangedBy','origin','stage','candidateIds','notes','riskLevel','timeScope','scope','sourceRunId'].includes(k)){
   const det=el('details');det.append(el('summary',labels[k]||k));det.addEventListener('toggle',()=>{if(det.open&&!det.dataset.loaded){const wrap=el('div');renderValue(v,wrap,0);det.append(wrap);det.dataset.loaded='1';}});dl.append(det);
  }else{dl.append(el('dt',labels[k]||k));const dd=el('dd');renderValue(v,dd,depth+1);dl.append(dd);}
 }container.append(dl);
}
function openSource(sid){const s=D.sources[sid];sourceFull=D.source_texts[s.sha256];$('viewTitle').textContent=s.path;$('viewMeta').textContent='Archivierte Kopie · SHA-256 '+s.sha256;$('sourceText').textContent=sourceFull;$('sourceHits').textContent='Vollständiger Originalinhalt';$('sourceSearch').value='';$('viewer').showModal();}
function evidenceBlock(b){const section=el('section',undefined,'material');section.append(el('h3',b.label));renderValue(b.data,section);return section;}
function record(c,f,form){
 if(!$('reviewer').value.trim()){alert('Bitte deinen Namen als prüfende Person eintragen.');$('reviewer').focus();return false;}
 const status=form.status.value,reason=form.reason.value.trim(),correction=form.correction.value.trim();
 if(!status){alert('Bitte eine Entscheidung auswählen.');return false;}
 if(status==='confirmed'&&f.ai_value===null){alert('Hier fehlt ein gesichertes KI-Einzelurteil. Bitte selbst bewerten oder unklar markieren.');return false;}
 if(['corrected','assessed'].includes(status)&&!correction){alert('Bitte dein eigenes Urteil eintragen.');form.correction.focus();return false;}
 if(status!=='confirmed'&&!reason){alert('Bitte die Änderung oder Unsicherheit kurz mit Belegstelle begründen.');form.reason.focus();return false;}
 if(status==='corrected'&&correction===String(f.ai_value)){alert('Dein Urteil ist unverändert. Wähle „Bestätigt“ und ergänze bei Bedarf eine abweichende Begründung.');return false;}
 if(!form.read.checked){alert('Bitte bestätigen, dass du die erforderlichen Originalbelege selbst geprüft hast.');return false;}
 const id=compoundId(c,f),old=state.answers[id]||null;
 const a={case_id:c.id,field_key:f.key,status,ai_value:f.ai_value,author_value:status==='confirmed'?f.ai_value:status==='unclear'?null:correction,reason:reason||(status==='confirmed'?'Vorhandene Begründung nach eigener Originalprüfung übernommen.':''),adopted_ai_reason:status==='confirmed'&&!reason,source_ids:c.sources,reviewer:$('reviewer').value.trim(),reviewed_originals:true,reviewed_at:new Date().toISOString()};
 state.answers[id]=a;state.reviewer=a.reviewer;state.history.push({at:a.reviewed_at,id,previous:old,next:a});state.position=c.id;persist();renderJudgments();return true;
}
function rating(c,f){
 const id=compoundId(c,f),a=state.answers[id];const section=el('section',undefined,'rating'+(a?' saved':'')+(a?.status==='unclear'?' unresolved':''));section.dataset.rating=id;
 section.append(el('h3',f.label));const ai=el('div',undefined,'ai');ai.append(el('strong','Bisheriges Urteil: '+val(f.ai_value)));ai.append(el('p',f.ai_reason,'reason'));section.append(ai);
 const form=el('div',undefined,'field-controls');const label=el('label','Deine Entscheidung');const status=el('select');status.setAttribute('aria-label','Entscheidung: '+f.label);
 for(const [v,t]of [['','Noch offen'],...(f.ai_value===null?[]:[['confirmed','Bestätigt nach Originalprüfung'],['corrected','Korrigiert']]),...(f.ai_value===null?[['assessed','Eigenes Urteil erfasst']]:[]),['unclear','Unklar / Beleg reicht nicht']]){const o=el('option',t);o.value=v;status.append(o);}status.value=a?.status||'';label.append(status);form.append(label);
 const corrlabel=el('label','Dein korrigiertes / eigenes Urteil');const correction=el('input');correction.setAttribute('aria-label','Eigenes Urteil: '+f.label);const listid='opts-'+id.replace(/[^a-zA-Z0-9]/g,'-');correction.setAttribute('list',listid);const list=el('datalist');list.id=listid;
 for(const v of f.options){const o=el('option');o.value=v;o.label=val(v);list.append(o);}correction.value=['corrected','assessed'].includes(a?.status)?a.author_value:'';corrlabel.append(correction,list);form.append(corrlabel);
 const why=el('label','Eigene Begründung / Belegstelle');const reason=el('textarea');reason.placeholder='Bei Bestätigung optional. Bei Korrektur oder Unklarheit bitte kurz begründen und die entscheidende Stelle nennen.';reason.setAttribute('aria-label','Begründung: '+f.label);reason.value=a?.adopted_ai_reason?'':a?.reason||'';why.append(reason);form.append(why);
 const check=el('label');check.style.display='flex';check.style.alignItems='start';check.style.fontWeight='400';const read=el('input');read.type='checkbox';read.checked=a?.reviewed_originals||false;check.append(read,el('span','Ich habe die für dieses Urteil erforderlichen Originalbelege selbst geprüft.'));form.append(check);
 const update=()=>{corrlabel.hidden=!['corrected','assessed'].includes(status.value);};status.addEventListener('change',()=>{update();dirty=true;});update();reason.addEventListener('input',()=>dirty=true);correction.addEventListener('input',()=>dirty=true);
 const actions=el('div',undefined,'actions');actions.append(btn('Urteil speichern',()=>record(c,f,{status,reason,correction,read}),'primary'));
 actions.append(btn('Speichern und weiter',()=>{if(record(c,f,{status,reason,correction,read})){if(fieldIndex<c.fields.length-1){fieldIndex++;renderJudgments();}else navigate(1);}}));
 if(a)actions.append(btn('Wieder öffnen',()=>{if(confirm('Dieses Antwortfeld wieder auf offen setzen? Die bisherige Antwort bleibt im Änderungsverlauf.')){state.history.push({at:new Date().toISOString(),id,previous:state.answers[id],next:null});delete state.answers[id];persist();renderJudgments();}}));
 actions.append(el('span',a?'Gespeichert: '+new Date(a.reviewed_at).toLocaleString('de-DE'):'Noch nicht geprüft','field-state'));form.append(actions);section.append(form);return section;
}
function contextSection(id){const c=D.contexts[id],det=el('details');det.append(el('summary',c.label));det.addEventListener('toggle',()=>{if(!det.open||det.dataset.loaded)return;det.dataset.loaded='1';const input=el('input');input.className='context-search';input.type='search';input.placeholder='Im vollständigen Kontext suchen …';input.setAttribute('aria-label','Kontext durchsuchen: '+c.label);const host=el('div');const raw=c.data;let values=Array.isArray(raw)?raw:(raw&&typeof raw==='object'?Object.entries(raw).map(([k,v])=>({Kennung:k,Inhalt:v})):null);
 // Core: für die Suche alle Items plus den unveränderten übrigen Kontext verfügbar halten.
 if(raw?.items&&Array.isArray(raw.items))values=raw.items;
 const show=()=>{host.replaceChildren();const q=input.value.toLowerCase().trim();const filtered=values?values.filter(x=>!q||JSON.stringify(x).toLowerCase().includes(q)):null;if(filtered){host.append(el('p',filtered.length+' von '+values.length+' Einträgen','notice'));renderValue(filtered,host);}else renderValue(raw,host);};input.addEventListener('input',show);det.append(input,host);for(const sid of c.sources)det.append(btn('Vollständige Originaldatei öffnen',()=>openSource(sid),'btn-link'));show();});return det;}
function confirmNavigation(){return !dirty||confirm('Es gibt noch nicht gespeicherte Eingaben in dieser Ansicht. Ansicht trotzdem wechseln?');}
function selectCurrent(id){if(!confirmNavigation())return;dirty=false;current=D.cases.find(c=>c.id===id)||visible[0]||null;if(current)state.position=current.id;renderCurrent();}
function renderJudgments(){
 fieldIndex=Math.max(0,Math.min(fieldIndex,current.fields.length-1));
 const nav=el('div',undefined,'criterion-nav');const select=el('select');select.setAttribute('aria-label','Bewertungskriterium auswählen');
 current.fields.forEach((f,i)=>{const o=el('option',(i+1)+'/'+current.fields.length+' · '+(isAnswered(state.answers[compoundId(current,f)])?'✓ ':'')+f.label);o.value=String(i);select.append(o);});select.value=String(fieldIndex);
 select.onchange=()=>{if(confirmNavigation()){dirty=false;fieldIndex=Number(select.value);renderJudgments();}};
 const buttons=el('div',undefined,'actions');const prev=btn('← Voriges Kriterium',()=>{if(confirmNavigation()){dirty=false;fieldIndex--;renderJudgments();}});prev.disabled=fieldIndex===0;
 const next=btn('Nächstes Kriterium →',()=>{if(confirmNavigation()){dirty=false;fieldIndex++;renderJudgments();}});next.disabled=fieldIndex===current.fields.length-1;buttons.append(prev,next);
 nav.append(el('label','Kriterium '+(fieldIndex+1)+' von '+current.fields.length),select,buttons);
 $('judgments').replaceChildren(el('h2','Deine Prüfung'),nav,rating(current,current.fields[fieldIndex]));
}
function renderCurrent(){
 $('empty').hidden=!!current;$('current').hidden=!current;if(!current)return;
 $('casePicker').value=current.id;$('caseHeading').replaceChildren(el('span',D.modules[current.module].title,'tag'),el('h2',current.title),el('p',current.id+' · '+current.fields.length+' getrennte Antwortfelder'));
 $('question').textContent=current.question;$('warning').hidden=!current.warning;$('warning').textContent=current.warning;
 $('evidence').replaceChildren(...current.blocks.filter(b=>b.data!==null&&b.data!==undefined).map((b,i)=>{if(i<2)return evidenceBlock(b);const d=el('details');d.append(el('summary',b.label));d.addEventListener('toggle',()=>{if(d.open&&!d.dataset.loaded){const host=el('div');renderValue(b.data,host);d.append(host);d.dataset.loaded='1';}});return d;}));
 fieldIndex=Math.max(0,current.fields.findIndex(f=>!isAnswered(state.answers[compoundId(current,f)])));renderJudgments();
 $('context').replaceChildren(el('h2','Vollständiger Kontext zum Nachschlagen'),...current.contexts.map(contextSection));
 const det=el('details');det.append(el('summary','Archivierte Originaldateien ('+current.sources.length+')'));const input=el('input');input.type='search';input.className='context-search';input.placeholder='Dateinamen filtern …';input.setAttribute('aria-label','Originaldateien filtern');const list=el('div',undefined,'source-list');const draw=()=>{list.replaceChildren();for(const id of current.sources){const s=D.sources[id];if(!s.path.toLowerCase().includes(input.value.toLowerCase()))continue;list.append(btn(s.path,()=>openSource(id)));}};input.addEventListener('input',draw);draw();det.append(input,list);$('originals').replaceChildren(det);
 $('prev').disabled=visible.indexOf(current)<=0;$('next').disabled=visible.indexOf(current)>=visible.length-1;updateProgress();
}
function rebuild(){const mod=$('module').value,f=$('filter').value,q=$('search').value.toLowerCase().trim();visible=D.cases.filter(c=>(!mod||c.module===mod)&&(!q||JSON.stringify(c).toLowerCase().includes(q))&&(f==='all'||f==='open'&&!done(c)||f==='done'&&done(c)||f==='unclear'&&c.fields.some(x=>state.answers[compoundId(c,x)]?.status==='unclear')||f==='changed'&&c.fields.some(x=>['corrected','assessed'].includes(state.answers[compoundId(c,x)]?.status))));
 $('casePicker').replaceChildren(...visible.map((c,i)=>{const o=el('option',(i+1)+'/'+visible.length+' · '+(done(c)?'✓ ':'')+c.title);o.value=c.id;return o;}));current=visible.find(c=>c.id===state.position)||visible[0]||null;renderCurrent();}
function navigate(delta){if(!confirmNavigation())return;const i=visible.indexOf(current)+delta;if(i<0||i>=visible.length)return;dirty=false;current=visible[i];state.position=current.id;renderCurrent();window.scrollTo({top:$('caseHeading').getBoundingClientRect().top+window.scrollY-20,behavior:'instant'});}
function download(name,obj){const blob=new Blob([JSON.stringify(obj,null,2)+'\n'],{type:'application/json'}),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000);}
function validateImport(x){if(x.schema!=='autorenpruefung-v1'||x.package_id!==D.package_id||!x.answers||typeof x.answers!=='object'||Array.isArray(x.answers))throw Error('Datei gehört nicht zu diesem Prüfungspaket.');for(const [id,a]of Object.entries(x.answers)){if(!fields.has(id)||!isAnswered(a)||!a.reviewed_originals||!a.reviewer||!a.reviewed_at)throw Error('Ungültiges Antwortfeld: '+id);const f=fields.get(id).f;if(a.status==='confirmed'&&(f.ai_value===null||a.author_value!==f.ai_value))throw Error('Ungültige Bestätigung: '+id);if(['corrected','assessed'].includes(a.status)&&(!a.author_value||!a.reason))throw Error('Unvollständige Korrektur: '+id);if(a.status==='unclear'&&!a.reason)throw Error('Unklar ohne Begründung: '+id);}}
 $('reviewer').value=state.reviewer;$('reviewer').addEventListener('change',()=>{state.reviewer=$('reviewer').value.trim();persist();});
 $('saveEffort').onclick=()=>{const effort=$('effort').value.trim();if(!effort)return;state.sessions.push({at:new Date().toISOString(),reviewer:$('reviewer').value.trim(),effort});$('effort').value='';persist();};
 $('module').append(el('option','Alle Module'));$('module').options[0].value='';for(const[m,s]of Object.entries(D.modules)){const o=el('option',s.title+' · '+s.cards+' Karten');o.value=m;$('module').append(o);} $('module').value=(D.cases.find(c=>c.id===state.position)||D.cases[0]).module;
 for(const id of ['module','filter'])$(id).addEventListener('change',()=>{if(confirmNavigation()){dirty=false;rebuild();}});$('search').addEventListener('input',()=>{if(!dirty)rebuild();});$('casePicker').addEventListener('change',e=>selectCurrent(e.target.value));$('prev').onclick=()=>navigate(-1);$('next').onclick=()=>navigate(1);
 $('export').disabled=false;$('export').onclick=()=>{state.reviewer=$('reviewer').value.trim();download('autorenpruefung-'+new Date().toISOString().replace(/[:.]/g,'-')+'.json',{...state,exported_at:new Date().toISOString(),summary:summary(),not_independent:true,not_blinded:true,unsaved_inputs_present:dirty});$('saveState').textContent='Export ausgelöst – Datei im Download-Ordner sichern.';};
 $('import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const x=JSON.parse(await file.text());validateImport(x);if(Object.keys(state.answers).length&&!confirm('Die importierte Datei ersetzt den aktuellen Antwortstand. Vorher nötigenfalls exportieren. Fortfahren?'))return;state={...state,...x};$('reviewer').value=state.reviewer||'';dirty=false;persist();rebuild();}catch(err){alert('Import abgebrochen: '+err.message);}finally{e.target.value='';}};
 $('closeView').onclick=()=>$('viewer').close();$('sourceSearch').oninput=()=>{const q=$('sourceSearch').value.toLowerCase().trim();if(!q){$('sourceText').textContent=sourceFull;$('sourceHits').textContent='Vollständiger Originalinhalt';return;}const lines=sourceFull.split('\n'),keep=new Set();let hits=0;lines.forEach((line,i)=>{if(line.toLowerCase().includes(q)){hits++;for(let j=Math.max(0,i-3);j<=Math.min(lines.length-1,i+3);j++)keep.add(j);}});$('sourceHits').textContent=hits+' Treffer; jeweils drei Kontextzeilen. Suche leeren für die vollständige Datei.';$('sourceText').textContent=[...keep].sort((a,b)=>a-b).map(i=>(i+1)+': '+lines[i]).join('\n');};
 window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});rebuild();updateProgress();$('saveState').textContent=storageOK?'Bereit · Antworten regelmäßig exportieren':'Browser-Speicher nicht verfügbar · regelmäßig exportieren';
 // Read-only snapshot for checking package mechanics; no synthetic human answers.
 window.REVIEW_STATUS=()=>({cases:D.cases.length,fields:fields.size,summary:summary(),current:current?.id,package_id:D.package_id});
})();
